name: Sync

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Coding
      uses: wearerequired/git-mirror-action@master
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SYNC_PRIVATE_KEY }}
      with:
          source-repo: "git@github.com:Guyutongxue/MyCppTutorial.git"
          destination-repo: "git@gitee.com:guyutongxue/MyCppTutorial.git"
